NAME = test

SRC_DIR = ../
BONUS_SRCS_DIR = ../

MAIN_FILES = main.c utils/string.c utils/print_errors.c

SRCS_FILES = get_next_line.c get_next_line_utils.c
BONUS_SRCS_FILES = get_next_line_bonus.c get_next_line_utils_bonus.c

SRCS = ${MAIN_FILES} ${addprefix ${SRC_DIR}, ${SRCS_FILES}}

BONUS_SRCS = ${MAIN_FILES} ${addprefix ${BONUS_SRCS_DIR}, ${BONUS_SRCS_FILES}}

OBJS = ${SRCS:.c=.o}

BONUS_OBJS = ${BONUS_SRCS:.c=.o}

BUFFER_SIZES = 32 9999 1 10000000
BSS = ${addprefix BS, ${BUFFER_SIZES}}

TESTS = test_negative_fd test_whatever_fd test_empty_file test_one_char \
		test_one_char_nl test_one_char_and_nl test_29chars test_29chars_nl \
		test_multi_lines test_multi_lines_32_chars test_big_line

CFLAGS = -Wall -Werror -Wextra -g# -fsanitize=address

CC = gcc ${CFLAGS}

all: ${NAME} run

${NAME}: ${OBJS}
	${CC} -I${SRC_DIR} ${OBJS} -o ${NAME}

bonus: ${BONUS_OBJS}
	${CC} -I${BONUS_SRCS_DIR} ${BONUS_OBJS} -o ${NAME}

test_%: %
	./${NAME} $<

%.o: %.c
	${CC} -I${SRC_DIR} -DBUFFER_SIZE=${BUFFER_SIZE} -c $< -o $@

BS%: BUFFER_SIZE = %
BS%: ${NAME}
	echo test $@

clean:
	rm -f ${OBJS}
	rm -f ${BONUS_OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all

run: Makefile ${TESTS}
	clear
	@./${NAME}
